#!/usr/bin/env bash
# /qompassai/Diver/scripts/generate
# Qompass AI Schema Luarocks Rootless Script
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
cd || /tmp
wget https://luarocks.org/releases/luarocks-3.13.0.tar.gz
tar zxpf luarocks-3.13.0.tar.gz
cd || luarocks-3.13.0
./configure \
  --prefix="$XDG_DATA_HOME/lua/luajit" \
  --with-lua-include=/usr/include/luajit-2.1 \
  --lua-version=5.1 \
  --sysconfdir="$XDG_CONFIG_HOME/luarocks"
make
make install