#!/usr/bin/env bash
# qompassai/Lua/scripts/rocks.sh
# Qompass AI Diver Lua Rocks Script
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
rocks=(
  api7-lua-resty-aws
  api7-lua-resty-jwt
  apkbuild
  amsfonts
  bit32
  botbye-openresty
  buildkite-test-collector
  busted
  busted-codewars
  busted-jsonl
  busted-htest
  busted-hjtest
  busted-stable
  busted-tl
  cldr
  cmdbuild
  debugkit
  debugkit-extra
  dkjson
  docker
  emmyluacodestyle
  gomaxmagick
  fffonion-lua-resty-kafka
  formatter
  fontproof
  fzf-lua
  fzy
  hash
  httpclient
  httprequestparser
  image_handler
  imagesize
  irc-formatter
  jsregexp
  kong-plugin-lua-resty-waf
  lanes
  latex-amsmath
  latex-base
  latex-cyrillic
  latex-fonts
  latex-graphics
  latex-tools
  latex-url
  ldoc
  libluajit
  lgi-async-extra
  lpeg
  lresty-cli
  lsqlite3complete
  lua-basex
  lua-cjson
  lua-lru
  luautf8
  luacheck
  luacheck-formatter-sonar
  lua_cliargs
  lua-csnappy
  luadbi
  luadbi-postgresql
  luadoc
  luadocumentor
  luafilesystem
  luafilesystem-ffi
  lua-genai
  luajit-xxhash
  lualatex
  lualdap
  lua-livr-extra
  luamake
  lua-markdown-extra
  lua-parser
  luaproc
  luar
  lua-resty-ada
  lua-resty-agoradynamickey
  lua-resty-arxignis
  lua-resty-aws
  lua-resty-aws-auth
  lua-resty-aws-signature
  lua-resty-azure
  lua-resty-balancer
  lua-resty-certificate-sso
  lua-resty-configure
  lua-resty-core
  lua-resty-couchdb
  lua-resty-dns-client
  lua-resty-etcd
  lua-resty-exec
  lua-resty-fastutils
  lua-resty-gcp
  lua-resty-grpc-gateway
  lua-resty-healthcheck
  lua-resty-hmac-ffi
  lua-resty-http
  lua-resty-jit-uuid
  lua-resty-jq
  lua-resty-jwt
  lua-resty-jwt-48606
  lua-resty-jwt-verification
  lua-resty-jwt2
  lua-resty-ldap
  lua-resty-libcjson
  lua-resty-ljsonschema
  lua-resty-lrucache
  lua-resty-luasocket
  lua-resty-mail
  lua-resty-mlcache
  lua-resty-mpd
  lua-resty-nettle
  lua-resty-oauth-proxy
  lua-resty-openidc
  lua-resty-openssl
  lua-resty-passwdqc
  lua-resty-paypal
  lua-resty-perf
  lua-resty-phantom-token
  lua-resty-postgres
  lua-resty-prettycjson
  lua-resty-radixtree
  lua-resty-redis
  lua-resty-redis-client
  lua-resty-redis-cluster
  lua-resty-redis-connector
  lua-resty-redis-util
  lua-resty-repl
  lua-resty-http
  lua-resty-reqargs
  lua-resty-requests
  lua_resty_netacea
  lua-resty-resolver
  lua-resty-rocketmq
  lua-resty-rollbar
  lua-resty-rsa
  lua-resty-s3-provider
  lua-resty-scrypt
  lua-resty-session
  lua-resty-shcache
  lua-resty-shell
  lua-resty-signal
  lua-resty-snappy
  lua-resty-socket
  lua-resty-t1k
  lua-resty-tags
  lua-resty-tarpit
  lua-resty-template
  lua-resty-thread
  lua-resty-timer-ng
  lua-resty-upload
  lua-resty-upstream-healthcheck-tls
  lua-resty-upstream-worker
  lua-resty-url
  lua-resty-uuid
  lua-resty-validation
  lua-resty-vardump
  lua-resty-waf
  lua-resty-websocket-kong
  lua-resty-websocket-proxy
  lua-resty-whitelist
  lua-resty-woothee
  lua-resty-worker-events
  lua-resty-xxhash
  luarestyredis
  luarocks
  luarocks-build-autotools
  luarocks-build-builtin-with-command
  luarocks-build-cpp
  luarocks-build-cyan
  luarocks-build-extended
  luarocks-build-fennel
  luarocks-build-l3build
  luarocks-build-list
  luarocks-build-lr-hooks
  luarocks-build-lls-addon
  luarocks-build-rust
  luarocks-build-rust-binary
  luarocks-build-lrocket
  luarocks-build-lrocket-next
  luarocks-build-rust-mlua
  luarocks-tag-release
  luarocks-build-treesitter-parser
  luarocks-build-tree-sitter-cli
  luarocks-build-treesitter-parser-cpp
  luarocks-build-xmake
  luarocks-fetch-gitrec
  lua-rtoml
  luasocket
  luaossl
  luasql-postgres
  luastruct
  luasql-postgres
  luasql-sqlite3
  luatext
  lua-term
  lua-toml
  luaunbound
  luautf8
  luv
  llv
  ltext
  lzlib
  magick
  markdown
  markdown.sile
  markdown2tex
  md5
  mod_lib_ldap
  mod_storage_ldap
  molde
  mi-lua-resty-worker-events
  neotest-busted
  nxx-lua-resty-cookie
  openssh-hash
  opentracing-openresty
  paged-markdown-3
  paged-markdown-3-pdf
  pkgbuild
  penlight
  postgrest
  pgvector
  platformdirs
  r1-lua-resty-waf
  rockbuild
  selene
  syntaxhighlight
  texrocks
  torch-buffer
  torch_cwrap
  torch-dataframe
  torch-dir-loader
  torch-graph-criterion
  torch_paths
  torch_threads
  torch_torch7
  torch-word-emb
  qluarocks
  quantum
  resty-dynacode
  resty-hostcheck
  resty-newrelic
  resty-raven
  resty-redis-cluster
  resty-redis-rate
  resty-route
  resty-shared-session
  resty-smtp
  rockspec2cmake
  santoku-resty
  sha1
  sha2
  string-format-all
  texture-share-vk
  tformat
  tree-sitter-agda
  tree-sitter-latex
  tree-sitter-markdown
  tree-sitter-markdown_inline
  tree-sitter-nim_format_string
  tree-sitter-php
  typecheck
  utf8
  utf8fix
  vscode-extensions
  wildcard_pattern
  wifi-lua-resty-kafka
  wsapi-openresty
  xmake
  xml-json
)
for rock in "${rocks[@]}"; do
  luarocks --lua-version=5.1 install "$rock" --force-lock
done
