return {
  "stevearc/conform.nvim",
  lazy = true,
  opts = {
    formatters_by_ft = {
      lua = { "stylua" },
      rust = { "rustfmt" },
      go = { "gofmt", "goimports" },
      python = { "black", "isort", "autopep8", "yapf" },
      ruby = { "rubocop" },
      javascript = { "prettierd", "eslint_d" },
      typescript = { "prettierd" },
      javascriptreact = { "prettierd" },
      typescriptreact = { "prettierd" },
      json = { "prettierd", "fixjson" },
      yaml = { "prettierd", "yamlfmt" },
      markdown = { "prettierd", "markdownlint" },
      html = { "prettierd", "htmlhint" },
      css = { "prettierd", "stylelint" },
      scss = { "prettierd", "stylelint" },
      c = { "clang-format" },
      cpp = { "clang-format" },
      bash = { "shfmt", "beautysh" },
      php = { "php-cs-fixer", "phpcbf" },
      kotlin = { "ktlint" },
      java = { "google-java-format" },
      terraform = { "terraform_fmt" },
      ansible = { "ansible-lint" },
      jsonnet = { "jsonnetfmt" },
      nix = { "nixpkgs-fmt" },
      dockerfile = { "hadolint" },
      sql = { "sql-formatter" },
      toml = { "taplo" },
    },
  },
}
